export enum GameActionEnum {
  CHANGE_ENTITY = "CHANGE_ENTITY",
  CHANGE_PLAYER_POSITION = "CHANGE_PLAYER_POSITION",
  CREATE_LEVEL = "CREATE_LEVEL",
  SET_DUNGEON_LEVEL = "SET_DUNGEON_LEVEL",
  DEDUCT_HP = "DEDUCT_HP",
  ADD_HP = "ADD_HP",
  PICKUP_WEAPON = "PICKUP_WEAPON",
  PICKUP_HEALTH_POTION = "PICKUP_HEALTH_POTION",
  PICKUP_ITEM = "PICKUP_ITEM",
}
