export enum GameActionEnum {
  ADD_HP_TO_PLAYER = "ADD_HP_TO_PLAYER",
  ATTACK_ENEMY = "ATTACK_ENEMY",
  CHANGE_ENTITY = "CHANGE_ENTITY",
  CREATE_LEVEL = "CREATE_LEVEL",
  CHANGE_PLAYER_POSITION = "CHANGE_PLAYER_POSITION",
  DEDUCT_HP_FROM_PLAYER = "DEDUCT_HP_FROM_PLAYER",
  EQUIP_OR_APPLY_ITEM = "EQUIP_OR_APPLY_ITEM",
  PICKUP_WEAPON = "PICKUP_WEAPON",
  PICKUP_HEALTH_POTION = "PICKUP_HEALTH_POTION",
  PICKUP_ITEM = "PICKUP_ITEM",
  SET_DUNGEON_LEVEL = "SET_DUNGEON_LEVEL",
}
